#!/usr/bin/env sh

## tagger - simple tagging system for any types of files

# Developer notes
# - 'tagger alias folder' for output alias and completion commands
# - add '_tagger_completion name folder` for aliases completion
# - check command for test tagger folder correctnes

set -e

SCRIPT="$(dirname $0)/tagger"

# Error handling and checks
err () {
    echo "$@" >&2
    exit
}

check () {
    name="$1"
    desc="$2"

    pexist "$name" "$desc"
    
    shift 2
    for chk in "$@"
    do
	"$chk" "$name" "$desc"
    done
		 
}

pexist () {
    [ -z "$1" ] &&
	err "$2 should be specified"
}

pnodir () {
    [ -d "$1" ] &&
	err "$2 already exist: $1"
}

pfile () {
    [ ! -f "$1" ] &&
	err "$2 should exist and be a file: $1"
}

pdir () {
    [ ! -d "$1" ] &&
	err "$2 should exist and be a directory: $1"
}

ptagged () {
    [ ! -f "$base/$1" ] &&
	err "$2 should be added before: $1"
}

ptag () {
    [ ! -d "$base/../$1" ] &&
	  err "$2 should exist: $1"
}

pbase () {
    [ ! -d "$base" ] &&
	err "$2 should be initialized by tagger: $1"
}

# Script logic

##
## Usage:
##
print_help () {
	awk '/^##/{print substr($0, 4);}' "$SCRIPT"
	exit
}

## tagger init _name_
## 	create new folder structure, under name, for
## 	keeping files and tags
##
init_tagger () {
    check "$1" "tagger folder" pnodir

    mkdir -p "$base"
}

## tagger add _folder_ _file_
## 	move file to tagger in tagger folder
##
add_file () {
    check "$1" "tagger folder" pdir pbase
    check "$2" "file" pfile

    mv "$2" "$base"
}

## tagger tag _folder_ _file_ _tag_
## 	add tag to file from tagger folder
##
tag_file () {
    check "$1" "tagger folder" pdir pbase
    check "$2" "file" ptagged
    check "$3" "tag"

    tag_folder="$1/$3"
    mkdir -p "$tag_folder"
    ln -s "../.base/$2" "$tag_folder"
}

## tagger untag _folder_ _file_ _tag_
## 	remove tag from file in tagger folder
##
untag_file () {
    check "$1" "tagger folder" pdir pbase
    check "$2" "file" ptagged
    check "$3" "tag" ptag

    tag_folder="$1/$3"
    rm -f "$tag_folder/$2"
}

## tagger ls _folder_
## 	list all files under tagger folder
##
list () {
    check "$1" "tagger folder" pdir pbase
    ls -1 "$base"
}

## tagger path _folder_ _file_
## 	get path for tagged file
##
path () {
    check "$1" "tagger folder" pdir pbase
    check "$2" "file" ptagged

    echo "$base/$2"
}

# Process arguments

[ "$#" -lt 1 ] && print_help

command="$1"
shift 1

base="$1/.base"

case "$command" in
    init)  init_tagger "$@" ;;
    add)   add_file "$@" ;;
    tag)   tag_file "$@" ;;
    untag) untag_file "$@" ;;
    ls)    list "$@" ;;
    path)  path "$@" ;;
    *) err "Unknown command $command" ;;
esac
