#!/usr/bin/env sh

## tagger - simple tagging system for any types of files

# Developer notes
# - 'tagger alias folder' for output alias and completion commands
# - add '_tagger_completion name folder` for aliases completion
# - check command for test tagger folder correctnes

set -e

SCRIPT=$(dirname "$0")/tagger

# Error handling and checks
err () {
    echo "$@" >&2
    exit
}

check () {
    name="$1"
    desc="$2"

    pexist "$name" "$desc"
    
    shift 2
    for chk in "$@"
    do
	"$chk" "$name" "$desc"
    done
		 
}

pexist () {
    [ -z "$1" ] &&
	err "$2 should be specified"
}

pnotagger () {
    [ -d "$base" ] &&
	err "$2 is already contain tagger: $1"
}

pfile () {
    [ ! -f "$1" ] &&
	err "$2 should exist and be a file: $1"
}

pdir () {
    [ ! -d "$1" ] &&
	err "$2 should exist and be a directory: $1"
}

ptagged () {
    [ ! -f "$base/$1" ] &&
	err "$2 should be added before: $1"
}

ptag () {
    [ ! -d "$base/../$1" ] &&
	  err "$2 should exist: $1"
}

pbase () {
    [ ! -d "$base" ] &&
	err "$2 should be initialized by tagger: $1"
}

# Script logic

##
## Usage:
##
## Common pattern is:
## 	tagger _folder_ command [arguments ...]
## 
print_help () {
	awk '/^##/{print substr($0, 4);}' "$SCRIPT"
	exit
}

## tagger _folder_ init
## 	create new folder structure, for
## 	keeping files and tags
##
init_tagger () {
    check "$1" "folder" pnotagger

    mkdir -p "$base"
}

## tagger _folder_ add _file_
## 	move file to tagger in tagger folder
##
add_file () {
    check "$1" "tagger folder" pdir pbase
    check "$3" "file" pfile

    mv "$3" "$base"
}

## tagger _folder_ tag _file_ _tag_
## 	add tag to file from tagger folder
##
tag_file () {
    check "$1" "tagger folder" pdir pbase
    check "$3" "file" ptagged
    check "$4" "tag"

    tag_folder="$1/$4"
    mkdir -p "$tag_folder"
    ln -s "../.base/$3" "$tag_folder"
}

## tagger _folder_ untag _file_ _tag_
## 	remove tag from file in tagger folder
##
untag_file () {
    check "$1" "tagger folder" pdir pbase
    check "$3" "file" ptagged
    check "$4" "tag" ptag

    tag_folder="$1/$4"
    rm -f "$tag_folder/$3"
}

## tagger _folder_ ls
## 	list all files under tagger folder
##
list () {
    check "$1" "tagger folder" pdir pbase
    ls -1 "$base"
}

## tagger _folder_ path _file_
## 	get path for tagged file
##
path () {
    check "$1" "tagger folder" pdir pbase
    check "$3" "file" ptagged

    echo "$base/$3"
}

# Process arguments

[ "$#" -lt 1 ] && print_help

base="$1/.base"
command="$2"

case "$command" in
    init)  init_tagger "$@" ;;
    add)   add_file "$@" ;;
    tag)   tag_file "$@" ;;
    untag) untag_file "$@" ;;
    ls)    list "$@" ;;
    path)  path "$@" ;;
    *) err "Unknown command $command" ;;
esac
